-- Create Expense table
CREATE TABLE public.expense (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id integer NOT NULL,
    description text NOT NULL,
    amount real NOT NULL,
    date timestamp WITHOUT TIME ZONE NOT NULL,
    category text NOT NULL,
    created_at timestamp WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at timestamp WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT expense_pkey PRIMARY KEY (id),
    CONSTRAINT expense_id_key UNIQUE (id),
    CONSTRAINT expense_description_check CHECK ((length(description) < 50))
) TABLESPACE pg_default;

-- Create index for Expense table
CREATE INDEX IF NOT EXISTS idx_expense_user_id_date ON public.expense USING btree (user_id, date) TABLESPACE pg_default;

-- Create Income table
CREATE TABLE public.income (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id integer NOT NULL,
    description text NOT NULL,
    amount real NOT NULL,
    date timestamp WITHOUT TIME ZONE NOT NULL,
    category text NOT NULL,
    created_at timestamp WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at timestamp WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT income_pkey PRIMARY KEY (id),
    CONSTRAINT income_id_key UNIQUE (id),
    CONSTRAINT income_description_check CHECK ((length(description) < 50))
) TABLESPACE pg_default;

-- Create index for Income table
CREATE INDEX IF NOT EXISTS idx_income_user_id_date ON public.income USING btree (user_id, date) TABLESPACE pg_default;

-- Create User table
CREATE TABLE public.user (
    user_id integer GENERATED BY DEFAULT AS IDENTITY,
    tz_offset real NOT NULL,
    created_at timestamp WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at timestamp WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_user_id_key UNIQUE (user_id)
) TABLESPACE pg_default;
